title: ac の Blog
email: wozhenlihainiyelihai@outlook.com
description: >- 
  I am AC, a human being with both beauty and talent.
url: "https://acca.github.io"
baseurl: ""
twitter_username:
github_username:  wozhenlihainiyelihai

# Build settings
theme: minima
plugins:
  - jekyll-feed
